version: "3.9"

networks:
    laravel:
        name: laravel
        driver: bridge

services:

    nginx:
        build:
            context: ./.docker-env/nginx
            dockerfile: nginx.dockerfile
        depends_on:
            - php
            # - mysql
        container_name: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www/html
        networks:
            - laravel

    php:
        build:
            context: ./.docker-env/php
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - ./:/var/www/html
        networks:
            - laravel

    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: laravel_db
            POSTGRES_USER: laravel_user
            POSTGRES_PASSWORD: secret_password
        volumes:
            - ./.pg-data:/var/lib/postgresql/data
        networks:
            - laravel

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6382:6379"
        networks:
            - laravel